### ISSUE TITLE
NodeTracker still stuck; tracker cycles through all servers EU&NA all respond "no Connection"

### ISSUE THREAD

**Issue by room101-dev** [HorizenOfficial/nodetracker#107]
I note this is an old problem going back to 2017, where its never resolved, look at the code, is clear if the connection fails the message is issued

1.) This is the ONLY secure node I have that has this problem
2.) Me thinks that horizen is banning or blocking IP's, ,but there is no confirmation, and no way to know
3.) This problem never has a solution, as here and on zend github, dozen's of posts but problem is never resolved
4.) I tried turning node off 24 hours, but still no connection, which leads me to think its an IP ban
5.) There are no diagnostics nothing from 'node app.js' to tell how to fix or diagnose the problem;
6.) The VPS are quite stingy with IP's and no willing to provide a new IP, so it would be useful to figure out how to get horizen to unblock
7.) Secret node docs talk about only one change, or when you clone an exists node to use old ID, and IP on new, because horizen only permits 1 of 3 changes at at a time; If this true it means the entire 'how to clone' an exists node is wrong, because if you follow the directions it doesn't work;

**Comment by ADumaine** [comment]
Some repsonses:

 - Individual ip addresses or subnets are not banned. The only ip addresses that may be banned are at the country level due to international restrictions.
 - There are several potential causes of this issue. Some client side, some server side.  
  - There are a couple changes to the tracking servers to help reduce the ocurrence, but it has not been deployed yet and is still to be scheduled.  The current workaround is to change home servers (see next item).
  - If stopping the nodetracking, waiting 30 seconds and restarting it does not work, a second technique may be tried:  Stop the nodetracker, change the home server in the config.json, restart the nodetracker. Make sure the nodetracker does not automatically restart while editing. This may cause two nodetrackers to run.  Changing the home server was mentioned here: https://github.com/HorizenOfficial/nodetracker/issues/101#issuecomment-1000907791
  
I am not sure what 'secret node docs' you are referring to.  But there have been hundreds of successful migrations to new servers.  https://horizenofficial.atlassian.net/wiki/spaces/ZEN/pages/1367015433/Migration+to+New+VPS+Provider

Yes only one item can be changed at time.  This is because each of these together are used to identify a node instead of having node operator/user accounts. If more than one were changed at one time, the node could not be identified properly.

**Comment by ADumaine** [comment]
Please reopen if there are still questions.

**Comment by room101-dev** [comment]
did fix, weeks ago, but I will re-cap for those who are stuck with this

**Comment by room101-dev** [comment]
**The problem is there is a hidden magic cookie left in the node-tracker path, so if it refuses to connect, then you need to delete the entire path and re-install;**
So how did I find this?
Well after a few days of playing around, I decided to re-install nodetracker into a new file-folder, and bingo it worked; Then I went back and did a DIFF and used 'ls -a' and found the magic-cookie file that was telling node tracker to self ban its own IP;
[ note of course I had tried re-installing earlier, but I was using the same path, and that magic-cookie was always there, so unless you do a full "rm -rf nodetrack-path/*" then you can't get rid of the nasty cookies ]
So it appears rather than black-listing IP's they have the nodes shut themselves down with a self-ban; hmmmm
Too bad there was no doc on this issue anywhere, but so now if somebody has this problem, they can fix it;
Note this transpired in the course of setting up a new node; What happened was node-tracker got ran, before the full node was 100%, so the node-tracker just black-listed itself given that it didn't have a full node that was 100%;
Of course people can say "don't install node tracker until you have a 100% full node running", but quite often its easy to jump ahead, especially given that on my most recent new VPS it now takes 2-3 days to download a full node; :(
Back in the day it was a few hours, now its like +65gb for the blockchain and it takes forever.

**Comment by ADumaine** [comment]
Do you have a copy of the "magic cookie" file or remember its contents?

This is odd because the tracking servers do not use a cookie with the nodetracker.  It is specifically set to false.

Cookies are only used on the web pages to track if the privacy banner has been checked and with the API.
